### ISSUE TITLE
Doesn't work with `brotli-size` 3.0.1

### ISSUE THREAD

**Issue by boris-petrov** [kaliber5/ember-cli-bundlesize#15]
Updating `brotli-size` from `0.1.0` to `3.0.1` causes `ember-cli-bundlesize` to blow up with `brotli.sync is not a function`.

**Comment by boris-petrov** [comment]
It does work with `4.0.0` though.
